services:
  kaset-more:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080;
    volumes:
      - ./logs:/app/logs
      - ./keys:/keys
    networks:
      - servernetwork

  webserver:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kaset-more
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/ssl:/cert
      - ./html:/etc/nginx/html/
    networks:
      - servernetwork

networks:
  servernetwork:
    driver: bridge
